version: "3.8"
services:
  frontend:
    image: chloepan/quirknotes_frontend:latest
    ports:
      - "3000:80"

  backend:
    image: chloepan/quirknotes_backend:latest
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
